name: FixTridentDupe
version: '1.0.0'
main: org.milkteamc.fixTridentDupe.FixTridentDupe
api-version: '1.20'
authors: [ Maoyue ]
description: Fix Minecraft Trident dupe (For Paper 1.20.6+ only)
website: https://www.milkteamc.org
